stages:
  preprocess_v0:
    cmd: python scripts/preprocess.py --dataset iris_v0

    deps:
      - scripts/preprocess.py
      - data/raw/iris_v0.csv

    outs:
      - data/processed/iris_v0_processed.csv

  preprocess_v1:
    cmd: python scripts/preprocess.py --dataset iris_v1

    deps:
      - scripts/preprocess.py
      - data/raw/iris_v1.csv

    outs:
      - data/processed/iris_v1_processed.csv

  train_iteration_1:
    cmd: python scripts/train.py --iteration 1

    deps:
      - scripts/train.py

      - data/processed/iris_v0_processed.csv

      - params.yaml

    outs:
      - models/model_iteration_1.pkl

      - metrics/metrics_iteration_1.json

  train_iteration_2:
    cmd: python scripts/train.py --iteration 2

    deps:
      - scripts/train.py

      - data/processed/iris_v1_processed.csv

      - params.yaml

    outs:
      - models/model_iteration_2.pkl

      - metrics/metrics_iteration_2.json
