dataset:
  raw:
    iteration1: data/raw/iris_v0.csv

    iteration2: data/raw/iris_v1.csv

  processed:
    iteration1: data/processed/iris_v0_processed.csv

    iteration2: data/processed/iris_v1_processed.csv

model:
  random_state: 42

  test_size: 0.2

  cv: 5

  parameters:
    n_estimators:
      - 50
      - 100
      - 200

    max_depth:
      - 3
      - 5
      - 10

    min_samples_split:
      - 2
      - 4

    criterion:
      - gini
      - entropy

mlflow:
  tracking_uri: http://35.196.169.169:5000/

  experiment_name: IITM_OPPE_IRIS

paths:
  model_dir: models

  metrics_dir: metrics
